name: unitTests.yml

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Running Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.4

      - name: Run Unit Tests
        run: mvn clean install
