on:
  push:
    branches:
      - main

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: postcode_api
          MYSQL_ROOT_PASSWORD: mypass
        ports:
          - 3306:3306
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"

      - name: Set up Maven
        run: mvn clean install -f ./pom.xml

      - name: Run Unit Tests
        run: mvn test --file pom.xml
